memory_type: episodic
policy:
    episodic:
        forget: oldest
        answer: latest
    semantic:
        forget: null
        answer: null
save_at: training-results/1118_170206
names_path: ./data/top-human-names
capacity:
    episodic: 2
    semantic: 0
semantic_knowledge_path: ./data/semantic-knowledge.json
pretrain_semantic: false
max_history: 1024
seed: 42
commonsense_prob: 0.5
weighting_mode: highest
