memory_type: semantic
policy:
    FIFO: true
    NRO: true
save_at: training-results/1102_203624
data_path: ./data/data.json
capacity:
    episodic: 0
    semantic: 256
pretrained_semantic: null
question_path: ./data/questions.json
creation_time: 1556382939
