memory_type: both
policy:
    episodic:
        forget: oldest
        answer: random
    semantic:
        forget: weakest
        answer: strongest
save_at: training-results/1114_203317
data_path: ./data/data.json
capacity:
    episodic: 8
    semantic: 8
pretrained_semantic: null
question_path: ./data/questions.json
seed: 42
