memory_type: both
policy:
    forget: FIFO
    duplicate_heads: false
save_at: training-results/1012_180504
data_path: ./data/data.json
capacity:
    episodic: 64
    semantic: 64
pretrained_semantic: null
