memory_type: both
policy:
    episodic:
        forget: oldest
        answer: latest
    semantic:
        forget: weakest
        answer: strongest
save_at: training-results/1114_210654
data_path: ./data/data.json
capacity:
    episodic: 4
    semantic: 4
pretrained_semantic: ./data/semantic-knowledge.json
question_path: ./data/questions.json
seed: 42
