memory_type: both
policy:
    episodic:
        forget: random
        answer: random
    semantic:
        forget: weakest
        answer: strongest
save_at: training-results/1114_211158
data_path: ./data/data.json
capacity:
    episodic: 64
    semantic: 64
pretrained_semantic: ./data/semantic-knowledge.json
question_path: ./data/questions.json
seed: 42
