memory_type: both
policy:
    episodic:
        forget: oldest
        answer: random
    semantic:
        forget: weakest
        answer: random
save_at: training-results/1114_210833
data_path: ./data/data.json
capacity:
    episodic: 8
    semantic: 8
pretrained_semantic: ./data/semantic-knowledge.json
question_path: ./data/questions.json
seed: 42
