memory_type: both
policy:
    episodic:
        forget: oldest
        answer: latest
    semantic:
        forget: random
        answer: strongest
save_at: training-results/1114_211518
data_path: ./data/data.json
capacity:
    episodic: 256
    semantic: 256
pretrained_semantic: ./data/semantic-knowledge.json
question_path: ./data/questions.json
seed: 42
