memory_type: both
policy:
    episodic:
        forget: oldest
        answer: random
    semantic:
        forget: weakest
        answer: random
save_at: training-results/1114_204802
data_path: ./data/data.json
capacity:
    episodic: 256
    semantic: 256
pretrained_semantic: null
question_path: ./data/questions.json
seed: 42
