seed: 42

env_params:
  env: EpisodicMemoryManageEnv
  capacity:
    episodic: 128
    semantic: 0
  max_history: 1024
  semantic_knowledge_path: ./data/semantic-knowledge.json
  names_path: ./data/top-human-names
  weighting_mode: highest
  commonsense_prob: 0.5
  memory_manage: RL_train
  question_answer: latest
  limits:
    heads: null
    tails: null
    names: null
    allow_spaces: true

dqn_params:
  dqn: mlp

training_params:
  gpus: 1
  max_epochs: 10
  val_check_interval: 1
  batch_size: 1
  lr: 0.01
  gamma: 0.99
  sync_rate: 10
  replay_size: 1000
  warm_start_size: 1000
  eps_last_frame: 1000
  eps_start: 1.0
  eps_end: 0.01
  episode_length: 200
  warm_start_steps: 1000
  log_every_n_steps: 100
