seed: 0

training_params:
  algorithm: policy_gradients
  device: cpu
  precision: 32
  num_processes: 16
  gamma: 0.00001
  learning_rate: 0.01
  batch_size: 1
  callbacks:
    monitor:
      metric: val_accuracy
      max_or_min: max
    early_stop:
      patience: 5
    lr_decay:
      patience: 3

strategies:
  episodic_memory_manage: train
  episodic_question_answer: latest
  semantic_memory_manage: weakest
  semantic_question_answer: strongest
  episodic_to_semantic: find_common
  episodic_semantic_question_answer: episodic_first
  pretrain_semantic: false
  capacity:
    episodic: 128
    semantic: 0
  policy_params:
    function_type: mlp
    embedding_dim: 4

generator_params:
  max_history: 1024
  semantic_knowledge_path: ./data/semantic-knowledge.json
  names_path: ./data/top-human-names
  weighting_mode: highest
  commonsense_prob: 0.5
  time_start_at: 0
  limits:
    heads: 40
    tails: 1
    names: 20
    allow_spaces: false
  disjoint_entities: true
