seed: 42

training_params:
  device: cuda
  precision: 32
  num_processes: 16
  batch_size: 128
  learning_rate: 0.001
  callbacks:
    monitor:
      metric: val_accuracy
      max_or_min: max
    early_stop:
      patience: 10
    lr_decay:
      patience: 3

dqn_params:
  gamma: 0
  eps_start: 0.9
  eps_end: 0.05
  eps_decay: 200
  target_update: 10
  replay_capacity: 10000

model_params:
  function_type: mlp
  embedding_dim: 4
  hidden_neurons: 8

strategies:
  episodic_memory_manage: train
  episodic_question_answer: latest
  semantic_memory_manage: weakest
  semantic_question_answer: strongest
  episodic_to_semantic: find_common
  episodic_semantic_question_answer: episodic_first
  pretrain_semantic: false
  capacity:
    episodic: 1
    semantic: 0

generator_params:
  max_history: 128
  semantic_knowledge_path: ./data/semantic-knowledge.json
  names_path: ./data/top-human-names
  weighting_mode: highest
  commonsense_prob: 0
  time_start_at: 0
  limits:
    heads: 2
    tails: 1
    names: 1
    allow_spaces: false
  disjoint_entities: true
