seed: 0

env_params:
  env: EpisodicMemoryManageEnv
  capacity:
    episodic: 4
    semantic: 0
  max_history: 64
  semantic_knowledge_path: ./data/semantic-knowledge.json
  names_path: ./data/top-human-names
  weighting_mode: highest
  commonsense_prob: 0.0
  memory_manage: RL_train
  question_answer: latest
  limits:
    heads: 4
    tails: 1
    names: 1
    allow_spaces: false
  override_time: true

dqn_params:
  dqn: mlp

callback_params:
  model_checkpoint:
    save_top_k: 3
    monitor: val_accuracy
    mode: max
    filename: "{epoch:03d}-{val_accuracy:.5f}"

trainer_params:
  gpus: 0
  max_epochs: 30
  val_check_interval: 1.0
  log_every_n_steps: 1

training_params:
  batch_size: 1
  lr: 0.00001
  gamma: 0
  sync_rate: 32
  replay_size: 64
  # warm_start_size: 4
  eps_last_epoch: 15
  eps_start: 1.0
  eps_end: 0.1
  episode_length: 64
  warm_start_steps: 64
  precision: 32
  num_processes: 64
