memory_type: both
policy:
    forget: FIFO
    duplicate_heads: false
save_at: training-results/1012_180452
data_path: ./data/data.json
capacity:
    episodic: 4
    semantic: 4
pretrained_semantic: null
