memory_type: semantic
policy:
    episodic:
        forget: null
        answer: null
    semantic:
        forget: random
        answer: strongest
save_at: training-results/1114_202656
data_path: ./data/data.json
capacity:
    episodic: 0
    semantic: 512
pretrained_semantic: null
question_path: ./data/questions.json
seed: 42
