memory_type: both
policy:
    FIFO: true
    NRO: true
save_at: training-results/1102_203751
data_path: ./data/data.json
capacity:
    episodic: 64
    semantic: 64
pretrained_semantic: null
question_path: ./data/questions.json
creation_time: 1556382939
