memory_type: both
policy:
    episodic:
        forget: oldest
        answer: random
    semantic:
        forget: random
        answer: strongest
save_at: training-results/1114_203309
data_path: ./data/data.json
capacity:
    episodic: 4
    semantic: 4
pretrained_semantic: null
question_path: ./data/questions.json
seed: 42
