memory_type: both
policy:
    episodic:
        forget: oldest
        answer: latest
    semantic:
        forget: weakest
        answer: random
save_at: training-results/1114_204011
data_path: ./data/data.json
capacity:
    episodic: 64
    semantic: 64
pretrained_semantic: null
question_path: ./data/questions.json
seed: 42
