memory_type: both
policy:
    forget: FIFO
    duplicate_heads: false
save_at: training-results/1012_180541
data_path: ./data/data.json
capacity:
    episodic: 32
    semantic: 32
pretrained_semantic: ./data/semantic-knowledge.json
