memory_type: both
policy:
    episodic:
        forget: oldest
        answer: latest
    semantic:
        forget: weakest
        answer: random
save_at: training-results/1114_202945
data_path: ./data/data.json
capacity:
    episodic: 1
    semantic: 1
pretrained_semantic: null
question_path: ./data/questions.json
seed: 42
