memory_type: both
policy:
    episodic:
        forget: random
        answer: random
    semantic:
        forget: weakest
        answer: strongest
save_at: training-results/1114_204800
data_path: ./data/data.json
capacity:
    episodic: 256
    semantic: 256
pretrained_semantic: null
question_path: ./data/questions.json
seed: 42
