memory_type: both
policy:
    episodic:
        forget: oldest
        answer: random
    semantic:
        forget: weakest
        answer: strongest
save_at: training-results/1114_203507
data_path: ./data/data.json
capacity:
    episodic: 16
    semantic: 16
pretrained_semantic: null
question_path: ./data/questions.json
seed: 42
