memory_type: episodic
policy:
    FIFO: true
    NRO: true
save_at: training-results/1102_213336
data_path: ./data/data.json
capacity:
    episodic: 256
    semantic: 0
pretrained_semantic: null
question_path: ./data/questions.json
creation_time: 1556382939
