memory_type: episodic
policy:
    forget: FIFO
    duplicate_heads: false
save_at: training-results/1012_180357
data_path: ./data/data.json
capacity:
    episodic: 8
    semantic: 0
pretrained_semantic: null
