memory_type: both
policy:
    FIFO: true
    NRO: true
save_at: training-results/1102_213739
data_path: ./data/data.json
capacity:
    episodic: 4
    semantic: 4
pretrained_semantic: ./data/semantic-knowledge.json
question_path: ./data/questions.json
creation_time: 1556382939
