memory_type: both
policy:
    forget: FIFO
    duplicate_heads: false
save_at: training-results/1012_180553
data_path: ./data/data.json
capacity:
    episodic: 256
    semantic: 256
pretrained_semantic: ./data/semantic-knowledge.json
