memory_type: both
policy:
    forget: FIFO
    duplicate_heads: false
save_at: training-results/1012_180455
data_path: ./data/data.json
capacity:
    episodic: 8
    semantic: 8
pretrained_semantic: null
