memory_type: both
policy:
    forget: FIFO
    duplicate_heads: false
save_at: training-results/1012_180446
data_path: ./data/data.json
capacity:
    episodic: 1
    semantic: 1
pretrained_semantic: null
