memory_type: both
policy:
    episodic:
        forget: oldest
        answer: latest
    semantic:
        forget: random
        answer: random
save_at: training-results/1114_205204
data_path: ./data/data.json
capacity:
    episodic: 256
    semantic: 256
pretrained_semantic: null
question_path: ./data/questions.json
seed: 42
