memory_type: semantic
policy:
    forget: FIFO
    duplicate_heads: false
save_at: training-results/1012_180443
data_path: ./data/data.json
capacity:
    episodic: 0
    semantic: 1024
pretrained_semantic: null
