memory_type: both
policy:
    episodic:
        forget: oldest
        answer: latest
    semantic:
        forget: random
        answer: random
save_at: training-results/1114_211247
data_path: ./data/data.json
capacity:
    episodic: 64
    semantic: 64
pretrained_semantic: ./data/semantic-knowledge.json
question_path: ./data/questions.json
seed: 42
