memory_type: both
policy:
    forget: FIFO
    duplicate_heads: false
save_at: training-results/1012_180507
data_path: ./data/data.json
capacity:
    episodic: 128
    semantic: 128
pretrained_semantic: null
