memory_type: episodic
policy:
    episodic:
        forget: random
        answer: random
    semantic:
        forget: null
        answer: null
save_at: training-results/1114_202148
data_path: ./data/data.json
capacity:
    episodic: 32
    semantic: 0
pretrained_semantic: null
question_path: ./data/questions.json
seed: 42
