memory_type: semantic
policy:
    episodic:
        forget: null
        answer: null
    semantic:
        forget: weakest
        answer: random
save_at: training-results/1114_202559
data_path: ./data/data.json
capacity:
    episodic: 0
    semantic: 256
pretrained_semantic: null
question_path: ./data/questions.json
seed: 42
