memory_type: both
policy:
    episodic:
        forget: oldest
        answer: random
    semantic:
        forget: random
        answer: strongest
save_at: training-results/1114_202950
data_path: ./data/data.json
capacity:
    episodic: 1
    semantic: 1
pretrained_semantic: null
question_path: ./data/questions.json
seed: 42
