memory_type: episodic
policy:
    forget: FIFO
    duplicate_heads: false
save_at: training-results/1012_180408
data_path: ./data/data.json
capacity:
    episodic: 256
    semantic: 0
pretrained_semantic: null
