memory_type: episodic
policy:
    episodic:
        forget: oldest
        answer: random
    semantic:
        forget: null
        answer: null
save_at: training-results/1114_202103
data_path: ./data/data.json
capacity:
    episodic: 8
    semantic: 0
pretrained_semantic: null
question_path: ./data/questions.json
seed: 42
